### ISSUE TITLE
An unknown error occurred verifying jackett indexers

### ISSUE THREAD

**Issue by slapcat** [lardbit/nefarious#202]
# Issue
I've had Nefarious with pretty much just the default setup + VPN running fine for a few months now. Suddenly it stopped working. I thought it was my deployment, so I completely erased every container, volume, and network and redeployed from scratch. 

# Troubleshooting
I setup one tracker that could test OK in Jackett, but then when I go to Nefarious dashboard to add the API token, I get the error "An unknown error occurred verifying jackett indexers." I know it is not the index, because when I remove them all, I still get a "Could not connect to jackett" error. ' Based on my testing and the errors below, it seems like the Nefarious container can't reach the Jackett container. I can reach it fine from the host, other computers on the network, and the transmission container, but not from the nefarious container.

# Logs
```
$ docker-compose -f docker-compose.transmission-vpn.yml ps
          Name                        Command                  State                                            Ports                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------------
nefarious_celery_1         /app/entrypoint-celery.sh        Up             80/tcp                                                                          
nefarious_jackett_1        /init                            Up                                                                                             
nefarious_nefarious_1      /app/entrypoint.sh               Up             0.0.0.0:8000->80/tcp                                                            
nefarious_redis_1          docker-entrypoint.sh redis ...   Up             6379/tcp                                                                        
nefarious_transmission_1   dumb-init /etc/openvpn/sta ...   Up (healthy)   0.0.0.0:51413->51413/tcp, 8118/tcp, 0.0.0.0:9091->9091/tcp,                     
                                                                           0.0.0.0:9117->9117/tcp                                                          
nefarious_watchtower_1     /watchtower --label-enable ...   Up             8080/tcp  
```

Foreground error log
```
HTTPConnectionPool(host='jackett', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey=02ufbuuy6lmy47fm3bxifbci2rj9lgcl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8541745850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Background error log
```
Processing request to watch [REDACTED]
TASK EXCEPTION
Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/env/lib/python3.9/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/env/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/env/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f37e0ff6400>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/env/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jackett', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey=02ufbuuy6lmy47fm3bxifbci2rj9lgcl&Query=Euphoria&Category%5B%5D=5000&Category%5B%5D=5010&Category%5B%5D=5020&Category%5B%5D=5030&Category%5B%5D=5040&Category%5B%5D=5060&Category%5B%5D=5070&Category%5B%5D=5080 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f37e0ff6400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Using `curl` from container and from host
```
$ docker exec -it nefarious_nefarious_1 curl http://jackett:9117
curl: (6) Could not resolve host: jackett

$ docker exec -it nefarious_nefarious_1 curl http://localhost:9117
curl: (7) Failed to connect to localhost port 9117: Connection refused

$ curl http://localhost:9117 -v
*   Trying 127.0.0.1:9117...
* Connected to localhost (127.0.0.1) port 9117 (#0)
> GET / HTTP/1.1
> Host: localhost:9117
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Date: Sun, 26 Jun 2022 23:19:10 GMT
< Server: Kestrel
< Location: /UI/Dashboard
< 
* Connection #0 to host localhost left intact
```

Jackett container network info
```
$ docker inspect `docker ps | grep jackett | awk '{print $1}'` | grep IP
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
```

**Comment by lardbit** [comment]
The [VPN setup expects](https://github.com/lardbit/nefarious/blob/master/docs/VPN.md#vpn) you to define the *jackett* host (in the nefarious settings page) as `transmission` since the [docker-compose file](https://github.com/lardbit/nefarious/blob/master/docker-compose.transmission-vpn.yml#L70
) routes itself through the transmission VPN.

Hopefully it's as simple as that, but let me know.

**Comment by slapcat** [comment]
Yes, that did it! Thanks for the quick response.
