### ISSUE TITLE
Error processing completed media

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#208]
IDK when but I have noticed that the completed media task fails. I have triggered it manually and this is the log:

```log
[2022-07-17 12:44:30,740: INFO/MainProcess] Connected to redis://redis:6379/0
[2022-07-17 12:44:30,744: INFO/MainProcess] mingle: searching for neighbors
[2022-07-17 12:44:31,279: INFO/Beat] beat: Starting...
[2022-07-17 12:44:31,755: INFO/MainProcess] mingle: all alone
[2022-07-17 12:44:31,767: INFO/MainProcess] celery@09b0ce615b02 ready.
[2022-07-17 12:44:35,570: INFO/MainProcess] Received task: nefarious.tasks.completed_media_task[5b891278-4a27-4c1a-a361-a2e41918898a]
INFO  2022-07-17 12:44:35,583  tasks 26  140453054121792  Media completed: The Good Doctor - Season 05
[2022-07-17 12:44:35,583: INFO/ForkPoolWorker-8] Media completed: The Good Doctor - Season 05
INFO  2022-07-17 12:44:35,588  tasks 26  140453054121792  Moving torrent data to "/downloads/complete/series/The Good Doctor"
[2022-07-17 12:44:35,588: INFO/ForkPoolWorker-8] Moving torrent data to "/downloads/complete/series/The Good Doctor"
INFO  2022-07-17 12:44:35,589  tasks 26  140453054121792  Renaming torrent file from "The Good Doctor S05 [PACK] [WEBDL AMZN 1080p ES AC3 2.0 EN DD+ 5.1 Subs][HDO] " to "The Good Doctor - Season 05"
[2022-07-17 12:44:35,589: INFO/ForkPoolWorker-8] Renaming torrent file from "The Good Doctor S05 [PACK] [WEBDL AMZN 1080p ES AC3 2.0 EN DD+ 5.1 Subs][HDO] " to "The Good Doctor - Season 05"
ERROR  2022-07-17 12:44:35,590  tasks 26  140453054121792  TASK EXCEPTION
Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/nefarious/tasks.py", line 214, in completed_media_task
    transmission_client.rename_torrent_path(torrent.id, torrent.name, new_name)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 801, in rename_torrent_path
    result = self._request('torrent-rename-path', args, torrent_id, True, timeout=timeout)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 262, in _request
    raise TransmissionError('Query failed with result \"%s\".' % (data['result']))

transmissionrpc.error.TransmissionError: Query failed with result "Invalid argument".
[2022-07-17 12:44:35,590: ERROR/ForkPoolWorker-8] TASK EXCEPTION
Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/nefarious/tasks.py", line 214, in completed_media_task
    transmission_client.rename_torrent_path(torrent.id, torrent.name, new_name)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 801, in rename_torrent_path
    result = self._request('torrent-rename-path', args, torrent_id, True, timeout=timeout)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 262, in _request
    raise TransmissionError('Query failed with result \"%s\".' % (data['result']))
transmissionrpc.error.TransmissionError: Query failed with result "Invalid argument".
[2022-07-17 12:44:35,590: ERROR/ForkPoolWorker-8] Task nefarious.tasks.completed_media_task[5b891278-4a27-4c1a-a361-a2e41918898a] raised unexpected: TransmissionError()
Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/env/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/nefarious/tasks.py", line 214, in completed_media_task
    transmission_client.rename_torrent_path(torrent.id, torrent.name, new_name)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 801, in rename_torrent_path
    result = self._request('torrent-rename-path', args, torrent_id, True, timeout=timeout)
  File "/env/lib/python3.9/site-packages/transmissionrpc/client.py", line 262, in _request
    raise TransmissionError('Query failed with result \"%s\".' % (data['result']))
transmissionrpc.error.TransmissionError: Query failed with result "Invalid argument".
```

I update automatically nefarious and transmission containers, so I'm running in latests version of both.

**Comment by lardbit** [comment]
I see that the torrent in question has a space at the very end, and this [transmission issue](https://github.com/transmission-remote-gui/transgui/issues/1317) sounds like a similar issue.

    "The Good Doctor S05 [PACK] [WEBDL AMZN 1080p ES AC3 2.0 EN DD+ 5.1 Subs][HDO] "

I just updated nefarious via pull request #209 to fail gracefully when transmission throws this exception during a rename operation so this error shouldn't prevent the "completed media" task from completing in the future.

I'm also wondering if nefarious should just strip white spaces at the beginning & end of the torrent name before doing the rename operation to maybe prevent transmission from choking on that edge case.

I'll test it out over the next day and will merge and let you know.

**Comment by JorTurFer** [comment]
hey,
Thanks because at least I have a tip that I can use to solve the problem :) 🙇

**Comment by lardbit** [comment]
Ok I just merged a fix, so nefarious should continue successfully when transmission throws that error.
