### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#81]
Hi,
I see that the image was updated whit night. After the update, I found this error in celery:
```python
[2021-01-14 08:41:52,554: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 08:41:52,561: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 08:41:53,576: INFO/MainProcess] mingle: all alone
[2021-01-14 08:41:53,588: INFO/MainProcess] celery@25676028042f ready.
[2021-01-14 08:41:54,961: INFO/Beat] beat: Starting...
[2021-01-14 08:41:54,969: ERROR/Beat] Removing corrupted schedule file 'celerybeat-schedule': error(13, 'Permission denied')
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 519, in setup_schedule
    self._store = self._open_schedule()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 509, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
[2021-01-14 08:41:54,971: ERROR/Beat] Process Beat
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 519, in setup_schedule
    self._store = self._open_schedule()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 509, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 707, in run
    self.service.start(embedded_process=True)
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 622, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/env/lib/python3.8/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 666, in scheduler
    return self.get_scheduler()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 657, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 501, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 257, in __init__
    self.setup_schedule()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 527, in setup_schedule
    self._store = self._destroy_open_corrupted_schedule(exc)
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 515, in _destroy_open_corrupted_schedule
    return self._open_schedule()
  File "/env/lib/python3.8/site-packages/celery/beat.py", line 509, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
[2021-01-14 08:41:54,972: WARNING/Beat] Process Beat:
[2021-01-14 08:41:54,972: WARNING/Beat] Traceback (most recent call last):
[2021-01-14 08:41:54,972: WARNING/Beat] File "/env/lib/python3.8/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
[2021-01-14 08:41:54,972: WARNING/Beat] KeyError: 'scheduler'
[2021-01-14 08:41:54,972: WARNING/Beat] During handling of the above exception, another exception occurred:
[2021-01-14 08:41:54,972: WARNING/Beat] Traceback (most recent call last):
[2021-01-14 08:41:54,972: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 519, in setup_schedule
    self._store = self._open_schedule()
[2021-01-14 08:41:54,972: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 509, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
[2021-01-14 08:41:54,972: WARNING/Beat] File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
[2021-01-14 08:41:54,972: WARNING/Beat] File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
[2021-01-14 08:41:54,972: WARNING/Beat] File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
[2021-01-14 08:41:54,972: WARNING/Beat] _gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
[2021-01-14 08:41:54,972: WARNING/Beat] During handling of the above exception, another exception occurred:
[2021-01-14 08:41:54,973: WARNING/Beat] Traceback (most recent call last):
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 707, in run
    self.service.start(embedded_process=True)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 622, in start
    humanize_seconds(self.scheduler.max_interval))
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 666, in scheduler
    return self.get_scheduler()
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 657, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 501, in __init__
    Scheduler.__init__(self, *args, **kwargs)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 257, in __init__
    self.setup_schedule()
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 527, in setup_schedule
    self._store = self._destroy_open_corrupted_schedule(exc)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 515, in _destroy_open_corrupted_schedule
    return self._open_schedule()
[2021-01-14 08:41:54,973: WARNING/Beat] File "/env/lib/python3.8/site-packages/celery/beat.py", line 509, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
[2021-01-14 08:41:54,973: WARNING/Beat] File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
[2021-01-14 08:41:54,973: WARNING/Beat] _gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
```

I tried to create from 0 all also, and I have the same error. I can't fount where is the file that breaks the container in order to continue debugging or trying. Sorry for this poor information

**Comment by lardbit** [comment]
You're right. The update broke something because I was trying to run nefarious as non-root. 

I'll fix that today. Thanks.

**Comment by lardbit** [comment]
I reverted the breaking changes, so you should see the update fixed soon.

**Comment by JorTurFer** [comment]
Now works fine!! 
Thanks!!!

**Comment by plagioriginal** [comment]
Hey @lardbit ,

Not sure if it is related to this, but I'm using the armv7 image and I too have an error now, and can't build nefarious.

```nefarious_1     | Operations to perform:
nefarious_1     |   Apply all migrations: admin, auth, authtoken, contenttypes, nefarious, sessions
nefarious_1     | Running migrations:
nefarious_1     |   No migrations to apply.
nefarious_1     | /app/docker-entrypoint.sh: 10: /app/docker-entrypoint.sh: authbind: not found
nefarious_1     | Operations to perform:
nefarious_1     |   Apply all migrations: admin, auth, authtoken, contenttypes, nefarious, sessions
nefarious_1     | Running migrations:
nefarious_1     |   No migrations to apply.
nefarious_1     | /app/docker-entrypoint.sh: 10: /app/docker-entrypoint.sh: authbind: not found```

**Comment by lardbit** [comment]
Hi @plagioriginal,  the ARM build actually just finished (it takes a bit longer to build).  Give it another 5 minutes or so and it should update to the previous version before the breaking changes.

**Comment by plagioriginal** [comment]
It's working, thank you :)
